includes:
  - base.yaml
model:
  model_name: GOODFormer
ood:
  ood_alg: GOODFormerAlg
  ood_param: 10
  extra_param:
    - 0.1
    - 0.01
train:
  max_epoch: 50
  lr: 0.0002
  mile_stones:
    - 100
  weight_decay: 0
log_file: exp_0
clean_save: true
