task: train
random_seed: 123
exp_round: null
log_file: default
gpu_idx: 0
ckpt_root: null
ckpt_dir: null
save_tag: null
other_saved: null
clean_save: False
pytest: False
pipeline: Pipeline
num_workers: 0
train:
  weight_decay: 0.
  save_gap: 10
  tr_ctn: False
  epoch: 0
  ctn_epoch: 0
  alpha: 0.2  # parameter for DANN
  stage_stones: []
  pre_train: 0
posenc_LapPE:
  pass_as_var: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 32
  layers: 2
  n_heads: 4
  post_layers: 0
  raw_norm_type: none
model:
  dim_hidden: 128
  num_heads: 4
  dim_ffn: 128
  dropout_rate: 0.2
  attn_dropout_rate: 0
dataset:
  dataloader_name: BaseDataLoader
  dataset_root: null
  generate: False
  dim_node: null
  dim_edge: null
  num_classes: null
  num_envs: null
  feat_dims: null
  edge_feat_dims: null
ood:
  extra_param: null